### ISSUE TITLE
package repositories override feature, doesn't remove the original repositories

### ISSUE THREAD

**Issue by vbusch** [jboss-container-images/concreate#92] opened 2017-10-10 13:42 UTC
When using the --overrides flag, it builds with the repositories from the original image.yaml, and the override_image.yaml.

image.yaml (upstream)
```
packages:
      repositories:
          - centos-base
      install:
          - openssl
```
override.yaml (downstream)
```
packages:
      repositories:
          - jboss-os
      install:
          - openssl  
```
Results in 
`Step 7 : RUN yum install -y --disablerepo=\* --enablerepo=jboss-rhel-os --enablerepo=centos-base openssl     && yum clean all &&     rpm -q  openssl`
RHEL does not like the base urls for the centos repos.  It should only contain the repositories from the override.yaml

**Comment by goldmann** [comment] 2017-10-10 13:48
I agree, cc @dbecvarik.

**Comment by dbecvarik** [comment] 2017-10-10 14:39
Then we need to change format of image descriptor. We don't support
overriding of arrays. Theyre merged. We cannot change this easily now. This
is how merging of layers works.

**Comment by goldmann** [comment] 2017-10-11 06:28
OK, let's try to find the story for overrides then.

We have two options:

1. Change current behavior of merging for repositories.
2. Encourage to use 3 descriptors: common, rhel, centos.

Opinions?

**Comment by dbecvarik** [comment] 2017-10-11 06:54
1. we cannot change merging of arrays easily - we need to merge arrays type consistently.
I don;t get second option. 
But what we can change except schema is override mechanism. Lets discuss this on BJ later. I'll prepare some options.

**Comment by goldmann** [comment] 2017-10-11 07:38
Instead of having a single image.yaml and override.yaml: have 3: common.yaml, rhel.yaml, centos.yaml. Both OS-specific descriptors would have OS-specific repositories and packages defined.

**Comment by dbecvarik** [comment] 2017-10-11 08:48
Another posiibility is to have repository defined in module. Then you can
override module, which is probably cleaner, because you can version a
module and also seems like native solution for me.

**Comment by rcernich** [comment] 2017-10-11 15:52
I think we don't worry about this.  Instead we should document how to design modules such that this is not a problem, e.g.:

./image.yaml
```yaml
...
modules:
  repositories:
  - name: project.common
    path: modules/common
  - name: project.platform
    path: modules/centos  # community builds by default
  install:
  - name: project.common.main
```

./modules/common/main/module.yaml
```yaml
name: project.common.main
modules:
  install:
  - name: project.platform.main  # do platform specific setup
packages:
  install:
  - openssl
```

./modules/platform/centos/module.yaml
```yaml
name: project.platform.main
packages:
  repositories:  # repository definitions specific to centos builds
  - centos-base
```

./modules/platform/rhel/module.yaml
```yaml
name: project.platform.main
packages:
  repositories:  # repository definitions specific to rhel builds
  - jboss-os
```

./overrides-rhel.yaml
```yaml
modules:
  repositories:
  - name: project.platform  # override platform repository to point to rhel instead of centos
    path: modules/rhel
```

``$ concreate build`` produces centos image
``$ concreate --overrides=overrides-rhel.yaml build`` produces rhel image.

**Comment by dbecvarik** [comment] 2017-10-11 16:26
Thanks. Thats exactly what I'm working on now! I'm also planing to create
some cookbook full of such best practices for concreate.

**Comment by vbusch** [comment] 2017-10-12 13:59
When you specify the repository in the image.yaml(centOS)
 ```
repositories:
  - name: project.platform
    path: modules/centos
```
concreate sometimes put the rhel one in `target/image/modules/project.platform.main/module.yaml`, when the centos one is expect.

Example that gets the wrong one: [https://github.com/vbusch/dockerfiles/tree/concreate/broker](https://github.com/vbusch/dockerfiles/tree/concreate/broker)
Example that gets the correct one: [https://github.com/vbusch/dockerfiles/tree/concreate/address-controller](https://github.com/vbusch/dockerfiles/tree/concreate/address-controller)
both built using: `concreate build` (only using the image.yaml file).  Not the image*rhel*.yaml files

I was hoping that it was just a typo.

**Comment by dbecvarik** [comment] 2017-10-13 11:09
Im looking at the issue, but whats in centos-base repo file?

**Comment by vbusch** [comment] 2017-10-13 11:52
Thank you @dbecvarik 

[centos-base]
name=CentOS-$releasever - Base
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
#baseurl=http://mirror.centos.org/centos/$releasever/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

**Comment by dbecvarik** [comment] 2017-10-13 12:04
Ok - the issue is probably caused by implicitly adding modules directory inside modules repository. I'll prepare fix for Monday.

**Comment by rcernich** [comment] 2017-10-14 03:47
Yes, it’s because of the implicit inclusion of ./modules/ where two modules
have the same id.  You could work around the issue by moving the platform
modules out of the modules folder, e.g. ./platform/centos and
./platform/rhel, then specify either platform/centos or platform/rhel for
the project.platform module repository.

On Oct 13, 2017, at 7:04 AM, David Becvarik <notifications@github.com>
wrote:

Ok - the issue is probably caused by implicitly adding modules directory
inside modules repository. I'll prepare fix for Monday.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jboss-container-images/concreate/issues/92#issuecomment-336433530>,
or mute the thread

**Closed** 2017-10-16 12:46 UTC
Labels: discussion, documentation, enhancement
