### ISSUE TITLE
Failed running concreate script on RHEL7

### ISSUE THREAD

**Issue by huiwan** [jboss-container-images/concreate#131] opened 2017-11-21 06:41 UTC
Something wrong with the scirpt on RHEL7:
[huwang@dhcp-144-102 jboss-webserver-3-image]$ pwd
/home/huwang/jboss-webserver-3-image

[huwang@dhcp-144-102 jboss-webserver-3-image]$ git branch
* webserver30
  webserver31-cp

[huwang@dhcp-144-102 jboss-webserver-3-image]$ concreate generate
Traceback (most recent call last):
  File "/usr/bin/concreate", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

Could someone can take a look?

Thanks,
Hui

**Comment by goldmann** [comment] 2017-11-21 11:41
Thanks, we will take a look at this soon!

**Comment by dbecvarik** [comment] 2017-11-21 18:35
can you please provide version of setup tools? both from rpm and pip (if you have pip installed). You should be able to use following commands:
``` bash
pip list | grep setuptools
rpm -qa | grep setuptools
```

**Comment by huiwan** [comment] 2017-11-22 07:36
```
[huwang@dhcp-144-102 ~]$ pip list | grep setuptools
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

[huwang@dhcp-144-102 ~]$ rpm -qa | grep setuptools
python-setuptools-0.9.8-7.el7.noarch

[huwang@dhcp-144-102 ~]$ rpm -qa | grep pip
python2-pip-8.1.2-5.el7.noarch

```
I think something wrong with the package requirements.py.

**Comment by dbecvarik** [comment] 2017-11-22 08:06
there is something  wrong in your setup, even pip doesn't work with the same error. I'll try to elaborate and will update later

**Comment by dbecvarik** [comment] 2017-11-22 12:13
How did you install concreate? via rpm or via pip?

**Comment by huiwan** [comment] 2017-11-23 02:36
Here is the document I use:
https://mojo.redhat.com/docs/DOC-1152771-jws-container-and-openshift-images-build-prerequisities-configuration-and-knowledge
```

[huwang@dhcp-144-102 ~]$ sudo curl https://copr.fedorainfracloud.org/coprs/goldmann/concreate/repo/epel-7/goldmann-concreate-epel-7.repo -o /etc/yum.repos.d/goldmann-concreate-epel-7.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   338  100   338    0     0    394      0 --:--:-- --:--:-- --:--:--   394
[huwang@dhcp-144-102 ~]$ sudo yum install python2-concreate
......
Updated:
  python2-concreate.noarch 0:1.3.0-1.el7.centos
Complete!
[huwang@dhcp-144-102 tomcat7]$ concreate generate
Traceback (most recent call last):
  File "/usr/bin/concreate", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
```

**Comment by dbecvarik** [comment] 2017-11-28 10:52
I was trying to investigate more, but i didn't find anything useful here. 
From listing you've provided even ```pip list``` command is failing with the same error - this command is totally unrelated to concreate, so it seem the issue is related to your machine setup and some python setuptools/pip version mismatch.
Similar issue is reported for example here https://stackoverflow.com/questions/42029545/pip-is-error-typeerror-call-takes-exactly-2-arguments-1-given

I'm suggesting to verify your environment in a way:
0) make sure, that you are using compatible version of python libraries
1) there is nothing '~/.local/lib/python*' for a root user
2) there was nothing install via ```pip install``` as a root or your current user
3) check via rpm --verify that all python packages are correct
4) remove any non rhel/non supported python packages like pip

This issue is not related to concreate, so I'm closing it.

**Closed by dbecvarik** 2017-11-28 10:52 UTC
